# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  client:
    build: ./client
    environment:
      - "API_URL=http://localhost:8080/api"
    ports:
      - "3000:80"
    depends_on:
      - "db"

  server:
    build: ./server
    environment:
      - "DB_HOST=db"
      - "DB_PORT=5432"
      - "DB_USER=postgres"
      - "DB_PASSWORD=example"
      - "DB_DATABASE=postgres"
    ports:
      - "8080:8080"
    depends_on:
      - "db"
